name: 'Integration Test'

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # daily

jobs:
  build:
    name: 'Integration Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Set up Java 17'
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: 'Set up Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Integration Test'
        run: ./gradlew build --dry-run
